spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: ${ALIYUN_SERVER_HOST}
    port: 6378
    database: 2
    timeout: 2000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
      max-total: 10
    password: 123456
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://${ALIYUN_SERVER_HOST}:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

## jwt相关配置
jwt:
  data:
    # jwt 加密密钥
    SECRET: jwtToken
    # 60s*60min*24h*7day
    expiration: 604800
## log日志处理相关配置
log:
  file:
    path: src/main/java/resources/log/log.txt

## oss服务相关配置
oss:
  enabled: true
  type: MINIO
  endpoint: http://${ALIYUN_SERVER_HOST}:9000
  access-key: minioadmin
  secret-key: minioadmin
  default-bucket-name: demo-bucket

