spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    password:
    timeout: 2000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
      max-total: 10
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


jwt:
  data:
    # jwt 加密密钥
    SECRET: jwtToken
    # 60s*60min*24h*7day
    expiration: 604800


