spring:
  redis:
    host: 8.130.73.219
    port: 6378
    database: 1
    password:
    timeout: 2000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
      max-total: 10